apiVersion: v2
name: github-value-helm
description: A Helm chart for Kubernetes
name: github-value # Name of the chart
description: A minimal Helm chart for deploying github-value application
type: application
version: 1.0.0 # Version of this Helm chart
appVersion: 1.0.0 # Version of the application
