{{- if eq .Values.deployment.mode "split-pods" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "github-value-helm.fullname" . }}-app
  labels:
    {{- include "github-value-helm.labels" . | nindent 4 }}
    component: app
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "github-value-helm.selectorLabels" . | nindent 6 }}
      component: app
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "github-value-helm.labels" . | nindent 8 }}
        component: app
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "github-value-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: wait-for-mysql
        image: {{ .Values.poller.image }}
        command:  {{ .Values.poller.command }}  
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }} #fix this
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.app.image.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.app.image.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.app.image.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.app.volumeMounts | nindent 12 }}
          envFrom:
            - configMapRef:
                name: github-value-config
            - secretRef:
                name: github-value-secret
      volumes:
        {{- toYaml .Values.app.volumes | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
# app-only deployment YAML here
{{- end }}