apiVersion: v1
kind: ConfigMap
metadata:
  name: github-value-config
  namespace: {{ .Values.namespace }}
data:
  PORT: {{ .Values.app.config.PORT | quote }}
  BASE_URL: {{ .Values.app.config.BASE_URL | quote }}
  GITHUB_APP_ID: {{  .Values.app.config.GITHUB_APP_ID | quote }}
  MONGODB_URI: {{ .Values.app.config.MONGODB_URI | quote }}
