apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: {{ .Values.namespace }}
data:
  # Add your database configuration data here
  MONGODB_DATABASE: {{ .Values.db.credentials.database | quote }}
