
apiVersion: v1
kind: Service
metadata:
  name: {{ include "github-value-helm.fullname" . }}-mysql
  labels:
    {{- include "github-value-helm.labels" . | nindent 4 }}
    component: mysql
spec:
  type: NodePort
  ports:
    - port: {{ .Values.db.containerPort }}
      targetPort: {{ .Values.db.containerPort }}
      protocol: TCP
      nodePort: 31000
      name: my-github-value-mysql-svc
  selector:
    {{- include "github-value-helm.selectorLabels" . | nindent 4 }}
    component: mysql
