{{- if eq .Values.deployment.mode "split-pods" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-value-chart-mysql
  labels:
    {{- include "github-value-helm.labels" . | nindent 4 }}
    component: mysql
spec:
  replicas: 1  # MySQL typically runs as a single instance
  selector:
    matchLabels:
      {{- include "github-value-helm.selectorLabels" . | nindent 6 }}
      component: mysql
  template:
    metadata:
      labels:
        {{- include "github-value-helm.labels" . | nindent 8 }}
        component: mysql
    spec:
      terminationGracePeriodSeconds: 60 
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: mysql
          image: {{ .Values.db.image}}:{{ .Values.db.image.tag | default "latest" }}
          ports:
            - name: sql
              protocol: TCP
              containerPort: {{ .Values.db.containerPort }}
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.db.credentials.database }}
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretName }}
                  key: {{ .Values.db.secretKey }}
          livenessProbe:
            {{- toYaml .Values.db.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.db.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.db.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.db.volumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .Values.db.volumes | nindent 8 }}
# MySQL-only deployment YAML 
{{- end }}