
apiVersion: v1
kind: Service
metadata:
  name: {{ include "github-value-helm.fullname" . }}-mysql
  labels:
    {{- include "github-value-helm.labels" . | nindent 4 }}
    component: mysql
spec:
  {{- if eq .Values.kubernetesEnvironment "gke" }}
  type: LoadBalancer
  {{- else if eq .Values.kubernetesEnvironment "dockerdesktop" or eq .Values.kubernetesEnvironment "openshift" }}
  type: NodePort
  {{- else }}
  type: ClusterIP
  {{- end }}
  ports:
    - port: {{ .Values.db.containerPort }}
      targetPort: {{ .Values.db.containerPort }}
      protocol: {{ .Values.dbservice.protocol | default "TCP" }}
      nodePort: {{ .Values.dbservice.nodePort }}
      name: my-github-value-mysql-svc
  selector:
    {{- include "github-value-helm.selectorLabels" . | nindent 4 }}
    component: mysql
