apiVersion: v1
kind: Service
metadata:
  name: github-value-chart-mysql
  labels:
    {{- include "github-value-helm.labels" . | nindent 4 }}
    component: mysql
spec:
  {{- if eq .Values.kubernetesEnvironment "gke" }}
  type: LoadBalancer
  {{- else if or (eq .Values.kubernetesEnvironment "dockerdesktop") (eq .Values.kubernetesEnvironment "openshift") }}
  type: NodePort
  {{- else }}
  type: ClusterIP
  {{- end }}
  ports:
    - port: {{ .Values.db.containerPort }}
      targetPort: {{ .Values.db.containerPort }}
      protocol: TCP
      nodePort: 31000  # Specific NodePort for external access
      name: my-github-value-mysql-svc
  selector:
    {{- include "github-value-helm.selectorLabels" . | nindent 4 }}
    component: mysql
