
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.db.persistentVolumeClaim.name }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    {{- toYaml .Values.db.persistentVolumeClaim.accessModes | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.db.persistentVolumeClaim.resources.requests.storage }}
  {{- if eq .Values.kubernetesEnvironment "gke" }}
  storageClassName: standard-rwo
  {{- else if eq .Values.kubernetesEnvironment "dockerdesktop" }}
  storageClassName: hostpath
  {{- else }}
  storageClassName: ""
  {{- end }}