
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.db.persistentVolumeClaim.name }}
  namespace: {{ .Values.namespace }}
  {{- if eq .Values.kubernetesEnvironment "gke" }}
  annotations:
    helm.sh/resource-policy: keep  # Prevent Helm from deleting this PVC
  {{- end }}
    
spec:
  accessModes:
    {{- toYaml .Values.db.persistentVolumeClaim.accessModes | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.db.persistentVolumeClaim.resources.requests.storage }}
  {{- if eq .Values.kubernetesEnvironment "aks" }}
  storageClassName: managed-csi
  {{- else if eq .Values.kubernetesEnvironment "dockerdesktop" }}
  storageClassName: hostpath
  {{- else if eq .Values.kubernetesEnvironment "gke" }}
  storageClassName: standard-rwo
  {{- else if eq .Values.kubernetesEnvironment "openshift" }}
  storageClassName: thin-csi
  {{- else }}
  storageClassName: ""
  {{- end }}