apiVersion: v1
kind: Secret
metadata:
  name: github-value-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MONGODB_PASSWORD: {{ .Values.app.config.MYSQL_PASSWORD | b64enc | quote }}
  GITHUB_APP_PRIVATE_KEY: {{ .Values.app.config.GITHUB_APP_PRIVATE_KEY | b64enc | quote }}
  GITHUB_WEBHOOK_SECRET: {{ .Values.app.config.GITHUB_WEBHOOK_SECRET | b64enc | quote }}
