apiVersion: v1
kind: Service
metadata:
  name: {{ include "github-value-helm.fullname" . }}
  labels:
    {{- include "github-value-helm.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.kubernetesEnvironment "gke" }}
  type: LoadBalancer
  {{- else if or (eq .Values.kubernetesEnvironment "dockerdesktop") (eq .Values.kubernetesEnvironment "aks") (eq .Values.kubernetesEnvironment "openshift") }}
  type: NodePort
  {{- else }}
  type: ClusterIP
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      nodePort: {{ .Values.service.nodePort }}
      name: my-github-value-port
  selector:
    {{- include "github-value-helm.selectorLabels" . | nindent 4 }}
